#!/usr/bin/env python3
"""Generate system/blockMeshDict for the T-junction with inlet resistor channels.

Adds a long narrow resistor channel upstream of each inlet — the 2D
hydraulic equivalent of the serpentine feed channels on a real chip. They
carry most of the driving pressure drop, which (a) moves the operating
point to controller-realistic kPa values (P_cont ~ 13 kPa, P_disp ~ 3 kPa
for the reference flow rates) and (b) bounds the flow surge when the water
meniscus breaches the ~800 Pa capillary entry threshold at the junction
(~6 mm/s instead of unbounded), widening the stable pressure window that
was razor-thin on the resistor-less geometry (see results/sweep_2026-07).

The mesh is a conformal patchwork over the grid lines below; blocks only
connect where their faces share all four vertices, so every region that
abuts a channel of different width is split into matching strips.

Run:  python3 gen_blockmesh.py   (writes system/blockMeshDict)
"""
from pathlib import Path

# ---- geometry (micrometres) -------------------------------------------------
W_MAIN = 150.0          # main channel width (y)
W_DISP = 75.0           # water inlet width (x)
W_RES_OIL = 75.0        # oil resistor width  -> R = 4.1e9 Pa s/m^2 per depth
L_RES_OIL = 3000.0      # oil resistor length
W_RES_WAT = 30.0        # water resistor width -> R = 1.8e9
L_RES_WAT = 4000.0      # water resistor length
DEPTH = 80.0            # extruded z thickness (2D: one cell, empty patches)

DX = 7.5                # transverse cell size in the two-phase region

# grid lines (block corners must lie on these)
XS = [-L_RES_OIL, 0.0, 537.5, 560.0, 590.0, 612.5, 1650.0]
YS = [0.0, 37.5, 112.5, 150.0, 450.0, 450.0 + L_RES_WAT]
ZS = [0.0, DEPTH]

# cells per x/y interval (index i = interval [line_i, line_i+1])
NX = [50, 72, 3, 4, 3, 138]     # resistor gets long streamwise cells
NY = [5, 10, 5, 40, 50]
# grading per interval (blockMesh simpleGrading: last/first cell ratio)
GX = [0.2, 1, 1, 1, 1, 1]       # oil resistor refines toward the junction
GY = [1, 1, 1, 1, 8]            # water resistor refines toward the junction

# fluid blocks as (x-interval, y-interval) index pairs
BLOCKS = (
    [(0, 1)]                                     # oil resistor (y strip 1)
    + [(1, j) for j in (0, 1, 2)]                # main channel, left of junction
    + [(i, j) for i in (2, 3, 4) for j in (0, 1, 2)]   # junction columns
    + [(5, j) for j in (0, 1, 2)]                # main channel, right (outlet)
    + [(i, 3) for i in (2, 3, 4)]                # water inlet strips
    + [(3, 4)]                                   # water resistor
)
# the oil resistor spans only the middle y strip
OIL_RES_YSTRIP = 1

# ---- mesh assembly ----------------------------------------------------------
verts: dict[tuple, int] = {}
def vid(x, y, z):
    key = (round(x, 3), round(y, 3), round(z, 3))
    if key not in verts:
        verts[key] = len(verts)
    return verts[key]

hexes = []       # (8 vertex ids, nx, ny, gx, gy)
face_count: dict[tuple, list] = {}

def add_block(ix, iy):
    x0, x1 = XS[ix], XS[ix + 1]
    y0, y1 = (YS[iy], YS[iy + 1])
    v = [vid(x0, y0, ZS[0]), vid(x1, y0, ZS[0]), vid(x1, y1, ZS[0]), vid(x0, y1, ZS[0]),
         vid(x0, y0, ZS[1]), vid(x1, y0, ZS[1]), vid(x1, y1, ZS[1]), vid(x0, y1, ZS[1])]
    hexes.append((v, NX[ix], NY[iy], GX[ix], GY[iy]))
    # hex faces (outward order): west, east, south, north, back(z0), front(z1)
    faces = [
        ('x', x0, (v[0], v[4], v[7], v[3])),
        ('x', x1, (v[1], v[2], v[6], v[5])),
        ('y', y0, (v[0], v[1], v[5], v[4])),
        ('y', y1, (v[3], v[7], v[6], v[2])),
        ('z', ZS[0], (v[0], v[3], v[2], v[1])),
        ('z', ZS[1], (v[4], v[5], v[6], v[7])),
    ]
    for axis, coord, quad in faces:
        face_count.setdefault(tuple(sorted(quad)), []).append((axis, coord, quad))

for ix, iy in BLOCKS:
    if ix == 0 and iy != OIL_RES_YSTRIP:
        continue
    add_block(ix, iy)

# external faces = faces belonging to exactly one block
patches = {'oil_inlet': [], 'water_inlet': [], 'outlet': [], 'walls': [], 'frontAndBack': []}
for entries in face_count.values():
    if len(entries) != 1:
        continue
    axis, coord, quad = entries[0]
    if axis == 'z':
        patches['frontAndBack'].append(quad)
    elif axis == 'x' and coord == XS[0]:
        patches['oil_inlet'].append(quad)
    elif axis == 'x' and coord == XS[-1]:
        patches['outlet'].append(quad)
    elif axis == 'y' and coord == YS[-1]:
        patches['water_inlet'].append(quad)
    else:
        patches['walls'].append(quad)

# ---- emit -------------------------------------------------------------------
lines = ["""/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by gen_blockmesh.py — edit that script, not this file.            |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

scale 1e-6;   // coordinates below are micrometres

vertices
("""]
for (x, y, z), i in sorted(verts.items(), key=lambda kv: kv[1]):
    lines.append(f"    ({x} {y} {z})   // {i}")
lines.append(");\n\nblocks\n(")
for v, nx, ny, gx, gy in hexes:
    lines.append(f"    hex ({' '.join(map(str, v))}) ({nx} {ny} 1) "
                 f"simpleGrading ({gx} {gy} 1)")
lines.append(");\n\nedges\n(\n);\n\nboundary\n(")
TYPES = {'oil_inlet': 'patch', 'water_inlet': 'patch', 'outlet': 'patch',
         'walls': 'wall', 'frontAndBack': 'empty'}
for name, quads in patches.items():
    lines.append(f"    {name}\n    {{\n        type {TYPES[name]};\n        faces\n        (")
    for q in quads:
        lines.append(f"            ({' '.join(map(str, q))})")
    lines.append("        );\n    }")
lines.append(");\n\nmergePatchPairs\n(\n);\n\n// ************************************************************************* //")

out = Path(__file__).parent / "system" / "blockMeshDict"
out.parent.mkdir(exist_ok=True)
out.write_text("\n".join(lines) + "\n")
ncells = sum(nx * ny for _, nx, ny, _, _ in hexes)
print(f"wrote {out}: {len(verts)} vertices, {len(hexes)} blocks, {ncells} cells")
