#!/usr/bin/env python3
"""Generate system/blockMeshDict for the 3D millable-chip T-junction twin.

The 2D cases model a mid-depth slice; a real 400x400 um square channel has
corner gutters -- the four corners a droplet's rounded interface can never
seal -- through which oil bypasses the forming droplet. 2D therefore
overstates junction blockage, biasing pinch-off timing and slug length.
This case quantifies that: the tjunction_2d_mill junction geometry, in 3D,
at the identical operating point (velocity inlets, Ca = 0.032, q = 0.25).

Design choices:
  - Junction region only (2 mm approach + junction + 4 mm outlet + 2 mm
    water leg). No feed serpentine/resistor: velocity inlets pin the flow
    rates directly, so upstream hydraulics are unnecessary for a fidelity
    check. x coordinates match tjunction_2d_mill's junction/outlet frame
    (junction at x = 2000-2400 um) so the droplet extractor's geometry
    parameters are identical.
  - Half-depth domain: wall at z = 0, symmetry plane at z = 200 um
    (mid-depth). Valid while the flow stays z-symmetric, which is expected
    at these capillary numbers; a full-depth spot check is the fallback if
    results look odd.

Run:  python3 gen_blockmesh.py             (DX = 20 um, ~84k cells)
      python3 gen_blockmesh.py --dx 13.3   (finer, for a later convergence pass)
"""
import argparse
from pathlib import Path

# ---- geometry (micrometres) -------------------------------------------------
W_MAIN = 400.0          # channel width (y) and full depth (z)
DEPTH = 400.0           # full channel depth; domain models half of it
L_APPROACH = 2000.0     # oil inlet -> junction left edge
L_OUTLET = 4000.0       # junction right edge -> outlet
L_WAT_LEG = 2000.0      # water inlet leg above the junction

BASE_DX = 20.0
_args = argparse.ArgumentParser()
_args.add_argument("--dx", type=float, default=BASE_DX,
                    help="Cell size (um), uniform in x/y/z; counts scale from "
                         "the BASE_DX=20 tuning.")
DX = _args.parse_args().dx

x_j0, x_j1 = L_APPROACH, L_APPROACH + W_MAIN
XS = [0.0, x_j0, x_j1, x_j1 + L_OUTLET]
YS = [0.0, W_MAIN, W_MAIN + L_WAT_LEG]
ZS = [0.0, DEPTH / 2.0]          # half-depth; symmetry at z = DEPTH/2

_scale = BASE_DX / DX
NX = [max(1, round(n * _scale)) for n in (100, 20, 200)]
NY = [max(1, round(n * _scale)) for n in (20, 100)]
NZ = max(1, round(10 * _scale))  # 10 cells across the half-depth at BASE_DX

# fluid blocks as (x-interval, y-interval) index pairs
BLOCKS = [(0, 0), (1, 0), (2, 0),   # main channel: approach, junction, outlet
          (1, 1)]                   # water leg above the junction

# ---- mesh assembly ----------------------------------------------------------
verts: dict[tuple, int] = {}
def vid(x, y, z):
    key = (round(x, 3), round(y, 3), round(z, 3))
    if key not in verts:
        verts[key] = len(verts)
    return verts[key]

hexes = []
face_count: dict[tuple, list] = {}

def add_block(ix, iy):
    x0, x1 = XS[ix], XS[ix + 1]
    y0, y1 = YS[iy], YS[iy + 1]
    v = [vid(x0, y0, ZS[0]), vid(x1, y0, ZS[0]), vid(x1, y1, ZS[0]), vid(x0, y1, ZS[0]),
         vid(x0, y0, ZS[1]), vid(x1, y0, ZS[1]), vid(x1, y1, ZS[1]), vid(x0, y1, ZS[1])]
    hexes.append((v, NX[ix], NY[iy], NZ))
    faces = [
        ('x', x0, (v[0], v[4], v[7], v[3])),
        ('x', x1, (v[1], v[2], v[6], v[5])),
        ('y', y0, (v[0], v[1], v[5], v[4])),
        ('y', y1, (v[3], v[7], v[6], v[2])),
        ('z', ZS[0], (v[0], v[3], v[2], v[1])),
        ('z', ZS[1], (v[4], v[5], v[6], v[7])),
    ]
    for axis, coord, quad in faces:
        face_count.setdefault(tuple(sorted(quad)), []).append((axis, coord, quad))

for ix, iy in BLOCKS:
    add_block(ix, iy)

patches = {'oil_inlet': [], 'water_inlet': [], 'outlet': [], 'symmetryPlane': [], 'walls': []}
for entries in face_count.values():
    if len(entries) != 1:
        continue
    axis, coord, quad = entries[0]
    if axis == 'x' and coord == XS[0]:
        patches['oil_inlet'].append(quad)
    elif axis == 'x' and coord == XS[-1]:
        patches['outlet'].append(quad)
    elif axis == 'y' and coord == YS[-1]:
        patches['water_inlet'].append(quad)
    elif axis == 'z' and coord == ZS[1]:
        patches['symmetryPlane'].append(quad)
    else:
        patches['walls'].append(quad)

# ---- emit -------------------------------------------------------------------
lines = ["""/*--------------------------------*- C++ -*----------------------------------*\\
| Generated by gen_blockmesh.py — edit that script, not this file.            |
\\*---------------------------------------------------------------------------*/
FoamFile
{
    version     2.0;
    format      ascii;
    class       dictionary;
    object      blockMeshDict;
}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

scale 1e-6;   // coordinates below are micrometres

vertices
("""]
for (x, y, z), i in sorted(verts.items(), key=lambda kv: kv[1]):
    lines.append(f"    ({x} {y} {z})   // {i}")
lines.append(");\n\nblocks\n(")
for v, nx, ny, nz in hexes:
    lines.append(f"    hex ({' '.join(map(str, v))}) ({nx} {ny} {nz}) "
                 f"simpleGrading (1 1 1)")
lines.append(");\n\nedges\n(\n);\n\nboundary\n(")
TYPES = {'oil_inlet': 'patch', 'water_inlet': 'patch', 'outlet': 'patch',
         'symmetryPlane': 'symmetry', 'walls': 'wall'}
for name, quads in patches.items():
    lines.append(f"    {name}\n    {{\n        type {TYPES[name]};\n        faces\n        (")
    for q in quads:
        lines.append(f"            ({' '.join(map(str, q))})")
    lines.append("        );\n    }")
lines.append(");\n\nmergePatchPairs\n(\n);\n\n// ************************************************************************* //")

out = Path(__file__).parent / "system" / "blockMeshDict"
out.parent.mkdir(exist_ok=True)
out.write_text("\n".join(lines) + "\n")
ncells = sum(nx * ny * nz for _, nx, ny, nz in hexes)
print(f"wrote {out}: {len(verts)} vertices, {len(hexes)} blocks, {ncells} cells")
